In [1]:
import numpy as np
import pandas as pd

In [2]:
data = np.genfromtxt("linear_sample.txt", skip_header=True, delimiter='\t')

In [3]:
print(data)

[[ 1.00000000e-02  4.03000000e+00  9.61684222e-01  4.99168422e+00]
 [ 2.00000000e-02  4.06000000e+00  4.05954190e-02  4.10059542e+00]
 [ 3.00000000e-02  4.09000000e+00  4.75610243e-01  4.56561024e+00]
 [ 4.00000000e-02  4.12000000e+00  9.79893005e-01  5.09989301e+00]
 [ 5.00000000e-02  4.15000000e+00 -5.47225743e-01  3.60277426e+00]
 [ 6.00000000e-02  4.18000000e+00 -7.13054985e-01  3.46694501e+00]
 [ 7.00000000e-02  4.21000000e+00 -1.60452481e-01  4.04954752e+00]
 [ 8.00000000e-02  4.24000000e+00 -6.47098121e-01  3.59290188e+00]
 [ 9.00000000e-02  4.27000000e+00 -6.32317560e-01  3.63768244e+00]
 [ 1.00000000e-01  4.30000000e+00 -8.17028738e-01  3.48297126e+00]
 [ 1.10000000e-01  4.33000000e+00 -4.71529830e-02  4.28284702e+00]
 [ 1.20000000e-01  4.36000000e+00  9.21330120e-02  4.45213301e+00]
 [ 1.30000000e-01  4.39000000e+00 -8.82853207e-01  3.50714679e+00]
 [ 1.40000000e-01  4.42000000e+00 -1.09359584e-01  4.31064042e+00]
 [ 1.50000000e-01  4.45000000e+00  5.47242625e-01  4.99724263e

In [4]:
x_data = data[:, 0]

In [6]:
print(x_data)

[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13 0.14
 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28
 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41 0.42
 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55 0.56
 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7
 0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83 0.84
 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98
 0.99 1.   1.01 1.02 1.03 1.04 1.05 1.06 1.07 1.08 1.09 1.1  1.11 1.12
 1.13 1.14 1.15 1.16 1.17 1.18 1.19 1.2  1.21 1.22 1.23 1.24 1.25 1.26
 1.27 1.28 1.29 1.3  1.31 1.32 1.33 1.34 1.35 1.36 1.37 1.38 1.39 1.4
 1.41 1.42 1.43 1.44 1.45 1.46 1.47 1.48 1.49 1.5  1.51 1.52 1.53 1.54
 1.55 1.56 1.57 1.58 1.59 1.6  1.61 1.62 1.63 1.64 1.65 1.66 1.67 1.68
 1.69 1.7  1.71 1.72 1.73 1.74 1.75 1.76 1.77 1.78 1.79 1.8  1.81 1.82
 1.83 1.84 1.85 1.86 1.87 1.88 1.89 1.9  1.91 1.92 1.93 1.94 1.95 1.96
 1.97 1.

In [7]:
type(x_data)

numpy.ndarray

In [9]:
x_data.shape

(199,)

In [10]:
x_input = np.reshape(x_data, [1, -1])

In [36]:
x_input.shape

(1, 199)

In [37]:
print(x_input)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13 0.14
  0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28
  0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41 0.42
  0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55 0.56
  0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7
  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83 0.84
  0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98
  0.99 1.   1.01 1.02 1.03 1.04 1.05 1.06 1.07 1.08 1.09 1.1  1.11 1.12
  1.13 1.14 1.15 1.16 1.17 1.18 1.19 1.2  1.21 1.22 1.23 1.24 1.25 1.26
  1.27 1.28 1.29 1.3  1.31 1.32 1.33 1.34 1.35 1.36 1.37 1.38 1.39 1.4
  1.41 1.42 1.43 1.44 1.45 1.46 1.47 1.48 1.49 1.5  1.51 1.52 1.53 1.54
  1.55 1.56 1.57 1.58 1.59 1.6  1.61 1.62 1.63 1.64 1.65 1.66 1.67 1.68
  1.69 1.7  1.71 1.72 1.73 1.74 1.75 1.76 1.77 1.78 1.79 1.8  1.81 1.82
  1.83 1.84 1.85 1.86 1.87 1.88 1.89 1.9  1.91 1.92 1.93 1.94 1.95

In [55]:
y_data = data[:, 3]

In [56]:
print(y_data)

[ 4.99168422  4.10059542  4.56561024  5.09989301  3.60277426  3.46694501
  4.04954752  3.59290188  3.63768244  3.48297126  4.28284702  4.45213301
  3.50714679  4.31064042  4.99724263  3.50997022  3.73788683  3.97749169
  4.46502247  4.19046008  4.60316064  5.36065402  3.76667951  4.16985499
  5.50121752  4.66522649  4.36067614  5.07924633  5.77467995  4.40633126
  4.80318733  5.71650576  4.05745523  5.40295269  5.25157751  4.39074025
  4.90614144  5.28097512  5.32864728  5.1236426   5.48996749  4.49504488
  5.90831401  5.70035279  5.68296219  6.30999959  5.26153649  5.89900224
  4.85654161  6.12069862  4.86188297  5.44054055  5.44725392  6.05400746
  6.09698693  4.88119112  6.28969297  6.05696311  6.58284201  5.60474806
  4.96760674  6.70266402  5.53432462  6.13723626  5.20296326  5.93855954
  6.79755701  5.96771483  6.02524899  6.30322494  7.09717626  5.65522518
  7.03035795  6.98098744  6.55824439  6.39953669  5.95084453  6.46837364
  6.37844013  5.80164499  5.52955822  6.72172811  6

In [57]:
type(y_data)

numpy.ndarray

In [58]:
y_true = np.reshape(y_data, [1, -1])

In [59]:
y_true.shape

(1, 199)

In [60]:
y_line = data[:, 1]

In [61]:
print(y_line)

[4.03 4.06 4.09 4.12 4.15 4.18 4.21 4.24 4.27 4.3  4.33 4.36 4.39 4.42
 4.45 4.48 4.51 4.54 4.57 4.6  4.63 4.66 4.69 4.72 4.75 4.78 4.81 4.84
 4.87 4.9  4.93 4.96 4.99 5.02 5.05 5.08 5.11 5.14 5.17 5.2  5.23 5.26
 5.29 5.32 5.35 5.38 5.41 5.44 5.47 5.5  5.53 5.56 5.59 5.62 5.65 5.68
 5.71 5.74 5.77 5.8  5.83 5.86 5.89 5.92 5.95 5.98 6.01 6.04 6.07 6.1
 6.13 6.16 6.19 6.22 6.25 6.28 6.31 6.34 6.37 6.4  6.43 6.46 6.49 6.52
 6.55 6.58 6.61 6.64 6.67 6.7  6.73 6.76 6.79 6.82 6.85 6.88 6.91 6.94
 6.97 7.   7.03 7.06 7.09 7.12 7.15 7.18 7.21 7.24 7.27 7.3  7.33 7.36
 7.39 7.42 7.45 7.48 7.51 7.54 7.57 7.6  7.63 7.66 7.69 7.72 7.75 7.78
 7.81 7.84 7.87 7.9  7.93 7.96 7.99 8.02 8.05 8.08 8.11 8.14 8.17 8.2
 8.23 8.26 8.29 8.32 8.35 8.38 8.41 8.44 8.47 8.5  8.53 8.56 8.59 8.62
 8.65 8.68 8.71 8.74 8.77 8.8  8.83 8.86 8.89 8.92 8.95 8.98 9.01 9.04
 9.07 9.1  9.13 9.16 9.19 9.22 9.25 9.28 9.31 9.34 9.37 9.4  9.43 9.46
 9.49 9.52 9.55 9.58 9.61 9.64 9.67 9.7  9.73 9.76 9.79 9.82 9.85 9.88
 9.91 9.

# tensorflow를 사용한 회귀식

In [62]:
import tensorflow as tf
tf.__version__

'2.3.1'

In [63]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

In [64]:
learning_rate = 0.001
display_step = 100
training_epoch = 30000

In [65]:
x = tf.placeholder(tf.float32, shape=[1, None])
y = tf.placeholder(tf.float32, shape=[1, None])

In [66]:
a = tf.Variable(tf.ones([1,1]))
b = tf.Variable(tf.ones([1,1]))

In [67]:
y_estimated = tf.add(tf.matmul(a, x), b)

In [68]:
error = tf.reduce_mean(tf.square(y - y_estimated))

In [69]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate)

In [70]:
model = optimizer.minimize(error)

In [71]:
sess = tf.Session()

In [72]:
init = tf.global_variables_initializer()

In [73]:
sess.run(init)

In [74]:
for i in range(0,  training_epoch):
    sess.run(model, feed_dict={x: x_input, y: y_true})
    if ((i % display_step) == 0):
        error_out = sess.run(error, feed_dict={x: x_input, y: y_true})
        a_out = sess.run(a, feed_dict={x: x_input, y: y_true})
        b_out = sess.run(b, feed_dict={x: x_input, y: y_true})
        print(i, "error = ", error_out, "  a = ", a_out, "  b = ", b_out)

0 error =  26.577229   a =  [[1.011354]]   b =  [[1.0100327]]
100 error =  11.36403   a =  [[1.9258461]]   b =  [[1.8252553]]
200 error =  5.0068216   a =  [[2.5105116]]   b =  [[2.3594403]]
300 error =  2.3478477   a =  [[2.8822322]]   b =  [[2.7118015]]
400 error =  1.2333977   a =  [[3.1165295]]   b =  [[2.9464543]]
500 error =  0.76412773   a =  [[3.2622025]]   b =  [[3.104838]]
600 error =  0.5644967   a =  [[3.3507771]]   b =  [[3.2137334]]
700 error =  0.4776721   a =  [[3.4026213]]   b =  [[3.2904563]]
800 error =  0.43815574   a =  [[3.4308932]]   b =  [[3.3461986]]
900 error =  0.41858575   a =  [[3.4440873]]   b =  [[3.3882]]
1000 error =  0.40752554   a =  [[3.4476893]]   b =  [[3.421142]]
1100 error =  0.40018773   a =  [[3.4452398]]   b =  [[3.4480593]]
1200 error =  0.39456457   a =  [[3.4390223]]   b =  [[3.470914]]
1300 error =  0.38980758   a =  [[3.43051]]   b =  [[3.490982]]
1400 error =  0.38555425   a =  [[3.4206474]]   b =  [[3.509089]]
1500 error =  0.38164437  

12700 error =  0.3202711   a =  [[3.0157824]]   b =  [[3.9980714]]
12800 error =  0.320267   a =  [[3.0153737]]   b =  [[3.9985566]]
12900 error =  0.32026312   a =  [[3.0149684]]   b =  [[3.9990335]]
13000 error =  0.3202596   a =  [[3.0145845]]   b =  [[3.9994867]]
13100 error =  0.32025617   a =  [[3.014203]]   b =  [[3.9999328]]
13200 error =  0.320253   a =  [[3.0138426]]   b =  [[4.000362]]
13300 error =  0.32024992   a =  [[3.013485]]   b =  [[4.000791]]
13400 error =  0.3202471   a =  [[3.013139]]   b =  [[4.0011888]]
13500 error =  0.3202445   a =  [[3.0128052]]   b =  [[4.00157]]
13600 error =  0.320242   a =  [[3.0124855]]   b =  [[4.0019517]]
13700 error =  0.32023957   a =  [[3.0121756]]   b =  [[4.002333]]
13800 error =  0.32023737   a =  [[3.0118656]]   b =  [[4.002687]]
13900 error =  0.32023537   a =  [[3.011576]]   b =  [[4.003021]]
14000 error =  0.3202334   a =  [[3.0112898]]   b =  [[4.0033545]]
14100 error =  0.3202315   a =  [[3.011011]]   b =  [[4.0036883]]
1420

25500 error =  0.32020184   a =  [[3.0024796]]   b =  [[4.013728]]
25600 error =  0.32020184   a =  [[3.0024796]]   b =  [[4.013728]]
25700 error =  0.32020184   a =  [[3.0024796]]   b =  [[4.013728]]
25800 error =  0.32020184   a =  [[3.0024796]]   b =  [[4.013728]]
25900 error =  0.32020184   a =  [[3.0024796]]   b =  [[4.013728]]
26000 error =  0.32020184   a =  [[3.0024796]]   b =  [[4.013728]]
26100 error =  0.32020184   a =  [[3.0024796]]   b =  [[4.013728]]
26200 error =  0.32020184   a =  [[3.0024796]]   b =  [[4.013728]]
26300 error =  0.32020184   a =  [[3.0024796]]   b =  [[4.013728]]
26400 error =  0.32020184   a =  [[3.0024796]]   b =  [[4.013728]]
26500 error =  0.32020184   a =  [[3.0024796]]   b =  [[4.013728]]
26600 error =  0.32020184   a =  [[3.0024796]]   b =  [[4.013728]]
26700 error =  0.32020184   a =  [[3.0024796]]   b =  [[4.013728]]
26800 error =  0.32020184   a =  [[3.0024796]]   b =  [[4.013728]]
26900 error =  0.32020184   a =  [[3.0024796]]   b =  [[4.0137