In [10]:
import tensorflow as tf

In [12]:
tf.version.VERSION

'2.3.1'

In [19]:
import tensorflow.compat.v1 as tf

In [50]:
tf.disable_v2_behavior()

# Computation Graph

In [24]:
matrix_a = [[1, 10], [2, 20], [3, 30]]

In [26]:
matrix_b = [[1, 1, 1], [2, 2, 2]]

In [28]:
matrix_c = tf.matmul(matrix_a, matrix_b)

In [29]:
type(matrix_a)

list

In [31]:
matrix_d = [[1, 100], [2, 200], [3, 300]]

In [33]:
matrix_plus = tf.add(matrix_a, matrix_d)

In [34]:
const_plus = tf.add(matrix_a, 1000)

In [36]:
const_minus = tf.subtract(matrix_a, 1000)

In [37]:
matrix_mul = tf.multiply(matrix_a, -1)

In [40]:
print(matrix_c)

Tensor("MatMul_1:0", shape=(3, 3), dtype=int32)


# Session

In [42]:
sess = tf.Session()

In [44]:
init = tf.global_variables_initializer()

In [46]:
sess.run(init)

In [54]:
C = sess.run(matrix_c)

In [56]:
Add = sess.run(const_plus)

In [58]:
Subst = sess.run(const_minus)

In [60]:
mul = sess.run(matrix_mul)

In [55]:
print(C)

[[21 21 21]
 [42 42 42]
 [63 63 63]]


In [59]:
print(Subst)

[[-999 -990]
 [-998 -980]
 [-997 -970]]


In [57]:
print(Add)

[[1001 1010]
 [1002 1020]
 [1003 1030]]


In [64]:
print(mul)

[[ -1 -10]
 [ -2 -20]
 [ -3 -30]]


### print에 session을 직접 입력

In [63]:
print(sess.run(const_plus))

[[1001 1010]
 [1002 1020]
 [1003 1030]]
